sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Bcells" "SC_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_cell"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Cholangiocyte" "SC_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_cell"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Erythroid" "SC_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_cell"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Hepatocyte" "SC_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_cell"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "LSECs" "SC_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_cell"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Macrophage" "SC_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_cell"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "NKTcell" "SC_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_cell"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Stellate" "SC_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_cell"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "PortalEndo" "SC_All_Manual_Core_Celltype_Markers" "All_Integrated_Manual" "donor" "single_cell"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "InfMac" "SC_All_Manual_Core_Celltype_Markers" "All_Integrated_Manual" "donor" "single_cell"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "NonInfMac" "SC_All_Manual_Core_Celltype_Markers" "All_Integrated_Manual" "donor" "single_cell"

sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Bcells" "SN_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_nuc"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Cholangiocyte" "SN_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_nuc"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Erythroid" "SN_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_nuc"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Hepatocyte" "SN_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_nuc"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "LSECs" "SN_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_nuc"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Macrophage" "SN_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_nuc"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "NKTcell" "SN_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_nuc"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "Stellate" "SN_All_Manual_Core_Celltype_Markers" "Manual_Core" "donor" "single_nuc"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "PortalEndo" "SN_All_Manual_Core_Celltype_Markers" "All_Integrated_Manual" "donor" "single_nuc"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "InfMac" "SN_All_Manual_Core_Celltype_Markers" "All_Integrated_Manual" "donor" "single_nuc"
sbatch Run_DE_Celltypes.sh "Sc_vs_sn_integrated_harmony_plus_analysis_Anno.rds" "NonInfMac" "SN_All_Manual_Core_Celltype_Markers" "All_Integrated_Manual" "donor" "single_nuc"

