
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "Bcells" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "CD3abTcells" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "CentralHep" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "Cholangiocyte" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "cvLSECs" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "Erythroid" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "InfMac" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "InterHep" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "NKcells" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "NonInfMac1" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "NonInfMac2" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "PortalEndo" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "PortalHep" "SC_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SC_Empty_harmony_plus_analysis.rds" "Stellate" "SC_Empty_harmony"


sbatch Run_DE_Celltypes.sh "SN_Empty_harmony_plus_analysis.rds" "Stellate" "SN_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SN_Empty_harmony_plus_analysis.rds" "cvLSECs" "SN_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SN_Empty_harmony_plus_analysis.rds" "CentralHep" "SN_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SN_Empty_harmony_plus_analysis.rds" "PortalEndo" "SN_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SN_Empty_harmony_plus_analysis.rds" "PortalHep" "SN_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SN_Empty_harmony_plus_analysis.rds" "CentralHep" "SN_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SN_Empty_harmony_plus_analysis.rds" "InterHep" "SN_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SN_Empty_harmony_plus_analysis.rds" "NonInfMac" "SN_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SN_Empty_harmony_plus_analysis.rds" "Tcell" "SN_Empty_harmony"
sbatch Run_DE_Celltypes.sh "SN_Empty_harmony_plus_analysis.rds" "Cholangiocyte" "SN_Empty_harmony"
